import pytest
from pathlib import Path
from codelens.walker import walk_repo, _is_auto_generated


class TestWalkRepo:
    def test_finds_python_files(self, tmp_path):
        (tmp_path / "main.py").write_text("x = 1")
        (tmp_path / "README.md").write_text("# docs")
        found = [p for _, p in walk_repo(tmp_path)]
        assert "main.py" in found
        assert "README.md" not in found

    def test_finds_typescript_files(self, tmp_path):
        (tmp_path / "app.ts").write_text("const x = 1;")
        (tmp_path / "comp.tsx").write_text("export default function() {}")
        found = [p for _, p in walk_repo(tmp_path)]
        assert "app.ts" in found
        assert "comp.tsx" in found

    def test_finds_javascript_files(self, tmp_path):
        (tmp_path / "index.js").write_text("module.exports = {}")
        found = [p for _, p in walk_repo(tmp_path)]
        assert "index.js" in found

    def test_skips_node_modules(self, tmp_path):
        nm = tmp_path / "node_modules" / "lib"
        nm.mkdir(parents=True)
        (nm / "index.js").write_text("module.exports = {}")
        (tmp_path / "app.py").write_text("x = 1")
        found = [p for _, p in walk_repo(tmp_path)]
        assert not any("node_modules" in p for p in found)
        assert "app.py" in found

    def test_skips_venv(self, tmp_path):
        venv = tmp_path / "venv" / "lib"
        venv.mkdir(parents=True)
        (venv / "site.py").write_text("pass")
        (tmp_path / "main.py").write_text("pass")
        found = [p for _, p in walk_repo(tmp_path)]
        assert not any("venv" in p for p in found)
        assert "main.py" in found

    def test_skips_pycache(self, tmp_path):
        cache = tmp_path / "__pycache__"
        cache.mkdir()
        (cache / "foo.py").write_text("pass")
        (tmp_path / "foo.py").write_text("pass")
        found = [p for _, p in walk_repo(tmp_path)]
        assert not any("__pycache__" in p for p in found)

    def test_skips_build_dist(self, tmp_path):
        for d in ("build", "dist"):
            sub = tmp_path / d
            sub.mkdir()
            (sub / "out.js").write_text("var x = 1;")
        (tmp_path / "src.py").write_text("x = 1")
        found = [p for _, p in walk_repo(tmp_path)]
        assert not any("build" in p or "dist" in p for p in found)

    def test_respects_gitignore(self, tmp_path):
        (tmp_path / ".gitignore").write_text("secret.py\n")
        (tmp_path / "secret.py").write_text("TOKEN = 'abc'")
        (tmp_path / "public.py").write_text("x = 1")
        found = [p for _, p in walk_repo(tmp_path)]
        assert "public.py" in found
        assert "secret.py" not in found

    def test_uses_posix_paths(self, tmp_path):
        sub = tmp_path / "src" / "auth"
        sub.mkdir(parents=True)
        (sub / "login.py").write_text("pass")
        found = [p for _, p in walk_repo(tmp_path)]
        assert "src/auth/login.py" in found
        assert not any("\\" in p for p in found)

    def test_yields_absolute_path(self, tmp_path):
        (tmp_path / "app.py").write_text("x = 1")
        results = list(walk_repo(tmp_path))
        assert len(results) == 1
        abs_path, rel = results[0]
        assert abs_path.is_absolute()
        assert abs_path.exists()

    def test_empty_repo(self, tmp_path):
        found = list(walk_repo(tmp_path))
        assert found == []

    def test_nested_structure(self, tmp_path):
        (tmp_path / "a" / "b" / "c").mkdir(parents=True)
        (tmp_path / "a" / "b" / "c" / "deep.py").write_text("pass")
        found = [p for _, p in walk_repo(tmp_path)]
        assert "a/b/c/deep.py" in found


class TestIsAutoGenerated:
    def test_detects_auto_generated_header(self, tmp_path):
        f = tmp_path / "gen.ts"
        f.write_bytes(b"// AUTO-GENERATED - do not edit\nexport const x = 1;\n")
        assert _is_auto_generated(f) is True

    def test_detects_code_generated_header(self, tmp_path):
        f = tmp_path / "gen.go"
        f.write_bytes(b"// Code generated by protoc-gen-go\npackage main\n")
        assert _is_auto_generated(f) is True

    def test_detects_do_not_edit(self, tmp_path):
        f = tmp_path / "gen.py"
        f.write_bytes(b"# DO NOT EDIT - generated file\nx = 1\n")
        assert _is_auto_generated(f) is True

    def test_normal_file_not_auto_generated(self, tmp_path):
        f = tmp_path / "normal.ts"
        f.write_text("export const x = 1;")
        assert _is_auto_generated(f) is False

    def test_large_file_is_auto_generated(self, tmp_path):
        f = tmp_path / "large.py"
        f.write_text("x = 1\n" * 5001)
        assert _is_auto_generated(f) is True

    def test_exactly_5000_lines_ok(self, tmp_path):
        f = tmp_path / "ok.py"
        f.write_text("x = 1\n" * 5000)
        assert _is_auto_generated(f) is False
